.TH SCRAM 1
.SH NAME
scram \- scramble words

.SH SYNOPSIS
scram

.SH DESCRIPTION
scram scrambles it's input, every word is shuffled after its letters
except the first and the last one. A word is a list of alphabetic
characters.

.SH EXAMPLES
.PP
.fi
.RS
$ scram </usr/share/dict/cracklib-small
.RE
.fi
scrambles every word in the dictionary.
.PP
.fi
.RS
$ curl https://gist.githubusercontent.com/remalhaut/811898a727f018be12d35da4cb94394f/raw/ba2856d4eb15754a1a96b61a4591cedc43f29b91/smog.md | scram
.RE
.fi
scramble a github gist I found.

.SH BUGS
Because hope does not close streams when it has ended reading them,
and /dev/urandom is opened every time a word is shuffled, shuf exceeds
the limit of streams fairly quickly and scram aborts.
.br
Possible solution: Fix the hope interpreter in this regard, write a different
random number generator.
.P
scram only supports ASCII.

.SH "SEE ALSO"
.IR rev(1),
.IR shuf(1)

.SH AUTHOR
pranomostro (pranomestro@gmail.com)
