.Dd May 11, 2017
.Dt SCRAM 1
.Os

.Sh NAME
.Nm scram
.Nd scramble words

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
scrambles its input, every word is shuffled except the first and last
letter. A word is a list of alphabetic characters. Any arguments are
ignored.

.Sh EXAMPLES
Scramble every word in the dictionary:
.Pp
.Dl $ grep -v '[^a-z]' </usr/share/dict/cracklib-small | shuf | scram
.Dl fdnier
.Dl coeomnmr
.Dl yhtsleonufus
.Dl ictnodrus
.Dl pnirotut
.Dl ...

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
.Nm
only supports ASCII.
.Pp
Because hope does not close streams after reading them, and /dev/urandom
is opened every time a word is shuffled, shuf exceeds the limit of
streams fairly quickly and scram aborts.

.Sh SEE ALSO
.Xr grep 1 ,
.Xr rev 1 ,
.Xr shuf 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
